config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  root 'users#subscribe_page'
  
  get 'subscribe' => 'users#subscribe_page'
  post 'subscribe_now' => 'users#subscribe'
  get 'unsubscribe' => 'users#unsubscribe_page'
  post 'unsubscribe_now' => 'users#unsubscribe'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :email, :presence   => true,
                    :format     => { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i },
                    :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def self.send_quotes_to_all
    quote=Quote.order("RANDOM()").first
    users=User.all
    for user in users do
      SubscriptionMailer.daily_email(user,quote).deliver_now
    end
  end

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:id, :quote)
    end
end

app/controllers/subscribe_controller.rb
class SubscribeController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def subscribe_page
    flash[:notice]=""
    render('subscribe')
  end

  def subscribe
    @subscriber = User.new
    @subscriber.email = params[:user][:email]
    if @subscriber.save then
      flash[:success] = "You were added sucessfully to the Subscribers."
      SubscriptionMailer.welcome_email(@subscriber).deliver_now
      redirect_to root_path
    else
      flash[:notice] = @subscriber.errors.full_messages
    end
    
  end
  
  def unsubscribe_page
    flash[:notice]=""
    render('unsubscribe')
  end


  def unsubscribe
    if  User.exists?(:email => params[:user][:email]) then
      subscriber = User.find_by_email(params[:user][:email])
      if subscriber.delete then
        flash[:success] = "You were removed sucessfully to the Subscribers."
        redirect_to root_path
      else
        flash[:notice] = @subscriber.errors.full_messages
      end
    else
      flash[:notice] = "User is not subscribed already"

    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper

end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/subscribe_helper.rb
module SubscribeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Subscriber</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

</body>
</html>

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :quote %><br>
    <%= f.text_field :quote %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Quote</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.id %></td>
        <td><%= quote.quote %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @quote.id %>
</p>

<p>
  <strong>Quote:</strong>
  <%= @quote.quote %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>

app/views/users/subscribe.html.erb
<h1>Subscribe to daily quotes :</h1>

<%= form_tag :action => "subscribe" do |f| %>
  <div class="field">
    <h3>email</h3>
    <%= text_field  "user","email"  %>
  </div>
  <div class="actions">
    <%= submit_tag "Subscribe" %>
  </div>
<% end %>

app/views/users/unsubscribe.html.erb
<h1>UnSubscribe from daily quotes :</h1>

<%= form_tag :action => "unsubscribe" do |f| %>
  <div class="field">
    <h3>email</h3>
    <%= text_field  "user","email"  %>
  </div>
  <div class="actions">
    <%= submit_tag "Unsubscribe" %>
  </div>
<% end %>